var unmodDevList=[];
unmodDevList=[
    {slot:"Obligatory masculine item", found: false},
    {slot:"Obligatory asian item", found: false},
    {slot:"Pretty background item", found: false},
    {slot:"Sales theme background", found: false},
    {slot:"Item easily ID'd by artist's recognizable style", found: false},
    {slot:"Item that looks a bit too crunchy", found: false},
    {slot:"Obligatory unisex item", found: false},
    {slot:"Obligatory paw item", found: false},
    {slot:"Paw item is a conversion of a human item", found: false},
    {slot:"Only 1 paw item throughout the sale", found: false},
    {slot:"1 paw bundle", found: false},
    {slot:"New unique paw item", found: false},
    {slot:"Great Value&trade; Final Fantasy theme", found:  false},
    {slot: "Another zodiac theme", found: false},
    {slot:"Another trunk RIG", found: false},
    {slot:"New artist pet scheme", found: false},
    {slot:"Rebranded old color scheme", found: false},
    {slot:"Color schemes are not matching with the season", found: false},
    {slot:"Barely noticable color difference from another color scheme", found: false},
    {slot:"Overused color scheme on overused recolored item", found: false},
    {slot:"Color scheme themed bundle", found: false},
    {slot:"There's atleast 1 item you like", found: false},
    {slot:"Certain poses from an item are good", found: false},
    {slot:"The item you least expected is good", found: false},
    {slot:"Items are in schemes you like", found: false},
    {slot:"Items are actually discounted", found: false},
    {slot:"You like all the items from the sale", found: false},
    {slot:"Item/recolor has glitched poses", found: false},
    {slot:"Questionable color placements", found: false},
    {slot:"70/30 split feminine to other items", found: false},
    {slot:"Feminine items have more dynamic poses", found: false},
    {slot:"Items are \"discounted\"", found: false},
    {slot:"Sales gimmick causes user outrage", found: false},
    {slot:"Reused item pose", found: false},
    {slot:"New item has more than 1 bewere cut", found: false},
    {slot:"Artist remembered that cutters exist", found: false},
    {slot:"Different hair cutters alter the hair in different ways", found: false},
    {slot:"Different bewere cutter alter the clothes in different ways", found: false},
    {slot:"Item uses one of the newer cutters", found: false},
    {slot:"\"Bought extra GC for the Sale.\"", found: false},
    {slot:"\"My GC is safe.\"", found: false},
    {slot:"\"Looks like a I have to wake up in the middle of the night to buy pixels.\"", found: false},
    {slot:"\"Schedule is not NA friendly.\"", found: false},
    {slot:"\"I don't like X item, except for the 1 non-clothing pose.\"",  found: false},
    {slot:"\"Hope I can buy X item on the MP!\"", found: false},
    {slot:"\"I don't think I will use X item, but want it for the background poses.\"", found: false},
    {slot:"Exclusive kinegg is locked behind a bundle", found: false},
    {slot:"Exclusive recolors locked behind a bundle", found: false},
    {slot:"Exclusive recolors locked behind a RIG", found: false},
    {slot:"Soft uwu style feminine item", found: false},
    {slot:"Sexy lady item", found: false},
    {slot:"Cute, frilly, dorito dress", found: false},
    {slot:"Disproportionate arms", found: false},
    {slot:"Leg pose with broken hips", found: false},
    {slot:"Tiny feet", found: false},
    {slot:"Claw fingers", found: false},
    {slot:"\"I have to pee\" leg pose", found: false},
    {slot:"Item has recycled poses", found: false},
    {slot:"Only 1 new masculine item in the entire sale", found: false},
    {slot:"Masculine item is overly bara", found: false},
    {slot:"Masculine item is elegant formalwear", found: false},
    {slot:"Sitting masculine legs", found: false},
    {slot:"Awkward standing pose", found: false},
    {slot:"Overpriced Bundle", found: false},
    {slot:"Expensive Limited Quantity Item", found: false},
    {slot:"Exclusive Sales Kinegg", found: false},
    {slot:"Kindred RIG with terrible odds and old Kineggs", found: false},
    {slot:"Expensive Kindred RIG", found: false},
    {slot:"No paw version of kin drop", found: false},
    {slot:"Kin item comes with a unique or useful pose", found: false},
    {slot:"Sales kin is OP", found: false},
    {slot:"Sales kin is the strongest kin in the game", found: false},
    {slot:"Sales Hub thread is \"Heated\"", found: false},
    {slot:"Prisma item as exclusive in Grab Bag", found: false},
    {slot:"Prisma item is an exclusive in a RIG", found: false},
    {slot:"Prisma item has low drop rate", found: false},
    {slot:"Prisma item is overpriced", found: false},
    {slot:"Background is the best pose", found: false},
    {slot:"Masculine item is vaguely masculine", found: false},
    {slot:"Past Sales item not discounted", found: false},
    {slot:"Direct Buy the Most Expensive Tickets", found: false}
];
