var unmodList=[];
unmodList=[
    "Zodiac theme",
    "Celestial/Heavenly theme",
    "Magical Fantasy RPG theme",
    "Sun/Moon theme",
    "Artists' persona theme",
    "Theme is a reference to old Gaia lore",
    "Ossidian vs Solair theme",
    "New and unique sales theme",
    "Alchemy",
    "New Kinegg",
    "New Color Schemes",
    "Terrible RIG odds",
    "Mihoyoverse reference",
    "FF14 reference",
    "Pop culture reference",
    "Monthly Collectible Bundle",
    "Flair RIG",
    "Flairs Bundle",
    "Limited Quanity Bundle",
    "Past Sales item",
    "Direct Buy Tickets",
    "Sale themed flairs",
    "Last day sales grab bag",
    "Bundle Exclusive recolor",
    "Themed Bundles",
    "SDPlus Select boxes",
    "Accessory sets",
    "CI release super early",
    "GIANT Rerelease CI",
    "New Talker",
    "Sporkles",
    "Flower/Plant Themed Item",
    "Big floofy hair",
    "Sales backgrounds are in Loyals",
    "Sales backgrounds are in Treehouse",
    "Sales backgrounds are freebies",
    "Stressed out Sales Hub",
    "Grab Bag exclusive recolor",
    "\"Love the item, it's in the wrong color scheme\"",
    "\"Love the color scheme, but the item doesn't work for me.\"",
    "**not released** glitch",
    "Fantasy Skins",
    "Prisma item is direct buy",
    "Prisma Bundle",
    "Homepage banner shows new sales items before release",
    "Staff leaks an item before release",
    "Waking up early to buy an item"
]
