var unmodList=[];
unmodList=[
    "Obligatory masculine item",
    "Obligatory asian item",
    "Pretty background item",
    "Sale theme background",
    "Item easily ID'd by artist's recognizable style",
    "Homepage picture shows new sale items before release",
    "Item that looks a bit too crunchy",
    "Obligatory unisex item",
    "Obligatory paw item",
    "Paw item is a conversion of a human item",
    "Only 1 paw item throughout the sale",
    "1 paw bundle",
    "New unique paw item",
    "Theme is a reference to old Gaia lore",
    "Ossidian vs Solair theme",
    "Great Value&trade; Final Fantasy theme",
    "Another zodiac theme",
    "Celestial/Heavenly theme",
    "Magical Fantasy RPG theme",
    "New and unique sale theme",
    "Alchemy",
    "Another trunk RIG",
    "Sale themed flairs",
    "Last day sale grab bag",
    "New Kinegg",
    "New artist pet scheme",
    "Rebranded old color scheme",
    "Color schemes are not matching with the season",
    "Barely noticable color difference from another color scheme",
    "Overused color scheme on overused recolored item",
    "Kin is a recolor",
    "Color scheme themed bundle",
    "There's atleast 1 item you like",
    "Certain poses from an item are good",
    "The item you least expected is good",
    "Items are in schemes you like",
    "Items are actually discounted",
    "You like all the items from the sale",
    "Item/recolor has glitched poses",
    "Questionable color placements",
    "70/30 split feminine to other items",
    "Feminine items have more dynamic poses",
    "Terrible RIG odds",
    "Items are \"discounted\"",
    "Sales gimmick causes user outrage",
    "Reused item pose",
    "New item has more than 1 bewere cut",
    "Artist remembered that cutters exist",
    "Different hair cutters alter the hair in different ways",
    "Different bewere cutter alter the clothes in different ways",
    "Item uses one of the newer cutters",
    "\"Bought extra GC for the Sale.\"",
    "\"My GC is safe.\"",
    "\"Looks like a I have to wake up in the middle of the night to buy pixels.\"",
    "\"Schedule is not NA friendly.\"",
    "\"I don't like X item, except for the 1 non-clothing pose.\"", 
    "\"Hope I can buy X item on the MP!\"",
    "\"I don't think I will use X item, but want it for the background poses.\"",
    "Exclusive kinegg is locked behind a bundle",
    "Exclusive recolors locked behind a bundle",
    "Exclusive recolors locked behind a RIG",
    "Soft uwu style feminine item",
    "Sexy lady item",
    "Cute, frilly, dorito dress",
    "Disproportionate arms",
    "Leg pose with broken hips",
    "Tiny feet",
    "Claw fingers",
    "\"I have to pee\" leg pose",
    "Sale backgrounds are in Loyals",
    "Sale backgrounds are in Treehouse",
    "Sale backgrounds are freebies",
    "Item has recycled poses",
    "Only 1 new masculine item in the entire sale",
    "Masculine item is super buff muscleman",
    "Masculine item is elegant formalwear",
    "Sitting masculine legs",
    "Awkward standing pose",
    "Limited Quanity Bundle",
    "Overpriced Bundle",
    "Expensive Limited Quantity Item",
    "Exclusive Sales Kinegg",
    "Kindred RIG with terrible odds and old Kineggs",
    "Expensive Kindred RIG",
    "No paw version of kin drop",
    "Kin item comes with a unique or useful pose",
    "Sales kin is OP",
    "Sales kin is the strongest kin in the game",
    "Sales Hub thread is \"Heated\""
    

];