var unmodList=[];
unmodList=[
{slot:"Zodiac theme", found: false},
{slot:"Celestial/Heavenly theme", found: false},
{slot:"Magical Fantasy RPG theme", found: false},
{slot:"Sun/Moon theme", found: false},
{slot:"Theme is a reference to old Gaia lore", found: false},
{slot:"Ossidian vs Solair theme", found: false},
{slot:"New and unique sales theme", found: false},
{slot:"Alchemy", found: false},
{slot:"New Kinegg", found: false},
{slot:"New Color Schemes", found: false},
{slot:"Terrible RIG odds", found: false},
{slot:"Mihoyoverse reference", found: false},
{slot:"FF14 reference", found: false},
{slot:"Pop culture reference", found: false},
{slot:"Monthly Collectible Bundle", found: false},
{slot:"Flair RIG", found: false},
{slot:"Flairs Bundle", found: false},
{slot:"Limited Quanity Bundle", found: false},
{slot:"Past Sales item", found: false},
{slot:"Direct Buy Tickets", found: false},
{slot:"Sale themed flairs", found: false},
{slot:"Last day sales grab bag", found: false},
{slot:"Bundle Exclusive recolor", found: false},
{slot:"Themed Bundles", found: false},
{slot:"SDPlus Select boxes", found: false},
{slot:"Accessory sets", found: false},
{slot:"CI release super early", found: false},
{slot:"GIANT Rerelease CI", found: false},
{slot:"New Talker", found: false},
{slot:"Sporkles", found: false},
{slot:"Flower/Plant Themed Item", found: false},
{slot:"Big floofy hair", found: false},
{slot:"Sales backgrounds are in Loyals", found: false},
{slot:"Sales backgrounds are in Treehouse", found: false},
{slot:"Sales backgrounds are freebies", found: false},
{slot:"Stressed out Sales Hub", found: false},
{slot:"Grab Bag exclusive recolor", found: false},
{slot:"\"Love the item, it's in the wrong color scheme\"", found: false},
{slot:"\"Love the color scheme, but the item doesn't work for me.\"", found: false},
{slot:"**not released** glitch", found: false},
{slot:"Fantasy Skins", found: false},
{slot:"Prisma item is direct buy", found: false},
{slot:"Prisma Bundle", found: false},
{slot:"Homepage banner shows new sales items before release", found: false},
{slot:"Staff leaks an item before release", found: false},
{slot:"Waking up early to nab an item", found: false}
];

